name: spatialdata
description: An open and universal framework for processing spatial omics data
keywords:
  - data
  - spatialomics
tools:
  - custom:
      description: An open and universal framework for processing spatial omics data
      homepage: https://github.com/scverse/spatialdata
      documentation: https://spatialdata.scverse.org/en/latest/
      licence: ["BSD 3-Clause"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample' ]
  - versions:
      type: file
      description: YML file containing software versions
      pattern: "*.yml"
  - lib_csv:
      type: bundle
      description: |
        Path to spatialomics data bundle (e.g., from Xeniumranger)

output:
  - spatialdata:
      type: folder
      description: Spatialdata folder
      pattern: "${meta.id}/spatialdata/*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@heylf"
