lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
  files_unchanged:
    - .gitignore
    - assets/nf-core-spatialxe_logo_light.png
    - docs/images/nf-core-spatialxe_logo_dark.png
    - docs/images/nf-core-spatialxe_logo_light.png
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Florian Heyl
  description: A pipeline for spatialomics Xenium data.
  force: false
  is_nfcore: true
  name: spatialxe
  org: nf-core
  outdir: .
  version: 1.0dev
