name: Feature request
description: Suggest an idea for the nf-core/spatialxe pipeline. Please write in the title as the first word *module* (suggestin a new module for spatialxe) or *implement* for general feature request.
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please describe your suggestion for a new feature. It might help to describe a problem or use case, plus any alternatives that you have considered.
    validations:
      required: true
