name: "segger_create_dataset"
description: Create a segger compatible dataset to speed up training and prediction of cell segmentations.
keywords:
  - segmentation
  - xenium
  - imaging
tools:
  - "segger":
      description: "Segger uses graph neural networks and heterogeneous graphs to offer efficient cell segmentation at unmatched precision and accuracy."
      homepage: "https://github.com/EliHei2/segger_dev"
      documentation: "https://elihei2.github.io/segger_dev/user_guide/"
      tool_dev_url: "https://github.com/EliHei2/segger_dev"
      doi: "tbd"
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'segger_run_id' ]`
    - base_dir:
        type: file
        description: |
          Directory containing the raw dataset (e.g., transcripts, boundaries).
output:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'segger_run_id' ]`
    - datasetdir:
        description: |
          Directory to save the processed Segger dataset (in PyTorch Geometric format).
  - - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@tobiaspk"
  - "@khersameesh24"
maintainers:
  - "@tobiaspk"
  - "@khersameesh24"
