name: "proseg2baysor"
description: Probabilistic cell segmentation for in situ spatial transcriptomics
keywords:
  - segmentation
  - cell segmentation
  - spatialomics
  - probabilistic segmentation
  - in situ spatial transcriptomics
tools:
  - "proseg":
      description: "Proseg (probabilistic segmentation) is a cell segmentation method for in situ spatial transcriptomics. Xenium, CosMx, and MERSCOPE platforms are currently supported."
      homepage: "https://github.com/dcjones/proseg/tree/main"
      documentation: "https://github.com/dcjones/proseg/blob/main/README.md"
      tool_dev_url: "https://github.com/dcjones/proseg"
      doi: ""
      licence: ["GNU Public License"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing run information
          e.g. `[ id:'run_id']`
    - cell_polygons:
        type: file
        description: |
          Cell polygons output file from the proseg xenium (format) run
        pattern: "cell-polygons.geojson.gz"
  - - transcript_metadata:
        type: file
        description: |
          Transcript metadata file output file from the proseg xenium (format) run
        pattern: "transcript-metadata.csv.gz"
output:
  - - meta:
        type: map
        description: |
          Groovy Map containing run information
          e.g. `[ id:'run_id']`
    - xr_polygons:
        type: file
        description: 2D polygons for each cell in GeoJSON format. These are flattened from 3D
        pattern: "xr-cell-polygons.geojson"
  - - xr_metadata:
        type: file
        description: Transcript ids, genes, revised positions, assignment probability
        pattern: "xr-transcript-metadata.csv"
  - - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
