name: "spatialconverter_parquet_to_csv"
description: Tool suite for spatial omics data conversions.
keywords:
  - xenium
tools:
  - "spatialconverter":
      description: "Collects functions to convert data formats for various types of data processing and analysis for spatial omics data."
      homepage: "https://github.com/heylf/spatialconverter"
      documentation: "https://github.com/heylf/spatialconverter"
      tool_dev_url: "https://github.com/heylf/spatialconverter"
      doi: "tbd"
      licence: [""]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'segger_run_id' ]`
    - transcripts:
        type: file
        description: |
          Transcript file in parquet format.
output:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'segger_run_id' ]`
    - transcripts_csv:
        type: file
        description: |
          Transcript file in csv format.
  - - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@heylf"
maintainers:
  - "@heylf"