name: "segger_train_model"
description: Train a Segger cell segmentation model using a segger-created dataset.
keywords:
  - segmentation
  - xenium
  - imaging
  - model-training
tools:
  - "segger":
      description: "Segger uses graph neural networks and heterogeneous graphs to offer efficient cell segmentation at unmatched precision and accuracy."
      homepage: "https://github.com/EliHei2/segger_dev"
      documentation: "https://elihei2.github.io/segger_dev/user_guide/"
      tool_dev_url: "https://github.com/EliHei2/segger_dev"
      doi: "tbd"
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'segger_run_id' ]`
    - dataset_dir:
        type: file
        description: |
          Directory to segger created dataset(s).
output:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'segger_run_id' ]`
    - trained_models:
        type: directory
        description: |
          Directory to save the trained model and checkpoints.
  - - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@tobiaspk"
  - "@khersameesh24"
maintainers:
  - "@tobiaspk"
  - "@khersameesh24"
