name: "split_transcripts"
description: Split transcripts along x & y axes
keywords:
  - baysor
  - transcripts
  - split_transcripts
tools:
  - "baysor":
    description: "Utility package to split transcripts for Baysor. Baysor is a tool that segments cells using spatial gene expression maps. Optionally, segmentation masks can be given as additional input."
    homepage: "https://kharchenkolab.github.io/Baysor/dev/"
    documentation: "https://kharchenkolab.github.io/Baysor/dev/"
    tool_dev_url: "https://github.com/kharchenkolab/Baysor"
    doi: "https://doi.org/10.1038/s41587-021-01044-w"
    licence: ["MIT license"]
    identifier:

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - transcripts:
        type: file
        description: transcripts.parquet file from the xenium bundle
        pattern: "*.parquet"
  - x_bins:
      type: integer
      description: number of slices along the x axis (default - 10)
  - y_bins:
      type: integer
      description: number of slices along the y axis (default - 10)

output:
  - - splits_csv:
        - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
        - "*.csv":
          type: file
          description: filtered transcripts.parquet
          pattern: "splits.csv"

  - - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
